### PR TITLE
Update txt2img2img.py

### LINKED ISSUE #10: TypeError: img2img() missing 2 required positional arguments
`TypeError: img2img() missing 2 required positional arguments: 'img2img_batch_input_dir' and 'img2img_batch_output_dir'`
I don't see any such configurable values in Automatic111's webui.

### PR DESCRIPTION
**Pull request by ghost**
Updates the script to support the latest version of AUTOMATIC1111/stable-diffusion-webui.

Tested working on commit hash: f2a4a2c3a672e22f088a7455d6039557370dd3f2

Fixes #10

### CODE REVIEW

**Comment by xueqing0622** [comment]
same problem：
 File "D:\stable-diffusion-webui-master\scripts\txt2img2img.py", line 243, in run
    img2img_result = modules.img2img.img2img(
TypeError: img2img() missing 2 required positional arguments: 'img2img_batch_input_dir' and 'img2img_batch_output_dir'

**Comment by ghost** [comment]
@xueqing0622 What version does the UI show, it's working on the latest version of AUTOMATIC1111/stable-diffusion-webui for me (82eb8ea452b1e63535c58d15ec6db2ad2342faa8):
image

**Comment by xueqing0622** [comment]
> @xueqing0622 What version does the UI show, it's working on the latest version of AUTOMATIC1111/stable-diffusion-webui for me (82eb8ea452b1e63535c58d15ec6db2ad2342faa8): image

My version is v1.0.0, how to download your version v1.0.1

**Comment by xueqing0622** [comment]
I update for you new version, still show  version is v1.0.0
A few steps forward, but show this
Detected 147035 transparent pixel(s). Your subject is 43.91059875488281% of the canvas.
Adjusted sampling steps to 16
Updated CFG scale to 6.980792122281005 and denoising strength to 0.6050019839310204
Error completing request
Arguments: ('xqman in city by wlop', '', 'None', 'None', 20, 0, False, False, 1, 1, 7, -1.0, -1.0, 0, 0, 0, False, 512, 512, False, False, 0.7, 3, False, False, None, '', False, 1, '', 4, '', True, False) {}
Traceback (most recent call last):
  File "D:\stable-diffusion-webui-master\modules\ui.py", line 184, in f
    res = list(func(*args, **kwargs))
  File "D:\stable-diffusion-webui-master\webui.py", line 64, in f
    res = func(*args, **kwargs)
  File "D:\stable-diffusion-webui-master\modules\txt2img.py", line 40, in txt2img
    processed = modules.scripts.scripts_txt2img.run(p, *args)
  File "D:\stable-diffusion-webui-master\modules\scripts.py", line 159, in run
    processed = script.run(p, *script_args)
  File "D:\stable-diffusion-webui-master\scripts\txt2img2img.py", line 204, in run
    img2img_result = modules.img2img.img2img(
  File "D:\stable-diffusion-webui-master\modules\img2img.py", line 124, in img2img
    processed = process_images(p)
  File "D:\stable-diffusion-webui-master\modules\processing.py", line 343, in process_images
    p.init(all_prompts, all_seeds, all_subseeds)
  File "D:\stable-diffusion-webui-master\modules\processing.py", line 559, in init
    self.sampler = samplers_for_img2img[self.sampler_index].constructor(self.sd_model)
IndexError: list index out of range

**Comment by xueqing0622** [comment]
by the way, how to change the commit hash

**Comment by ghost** [comment]
> by the way, how to change the commit hash

This git pull is a request for the owner of this program/script, @ThereforeGames , to update the script. If you run `git pull` in the command line/terminal it wont work, it will just download @ThereforeGames version 1.0.0. Try this, save this file as `txt2img2img.py`, replacing the existing one in your /scripts:
https://raw.githubusercontent.com/ThereforeGames/txt2img2img/1373592ab80226284b5e2fd681218c54debad249/scripts/txt2img2img.py

**Comment by xueqing0622** [comment]
> > by the way, how to change the commit hash
> 
> This git pull is a request for the owner of this program/script, @ThereforeGames , to update the script. If you run `git pull` in the command line/terminal it wont work, it will just download @ThereforeGames version 1.0.0. Try this, save this file as `txt2img2img.py`, replacing the existing one in your /scripts: https://raw.githubusercontent.com/ThereforeGames/txt2img2img/1373592ab80226284b5e2fd681218c54debad249/scripts/txt2img2img.py

Ok, it can work now. This has troubled me for several days. Thank you for your help!  
Have a nice day

**Pull request closed without merging**
